#include "toBmp.h"


#define WHITE   ((1 << 24) - 1)
#define RED     ((1 << 24) - 1 - GREEN - BLUE)
#define GREEN   ((1 << 16) - 1 - BLUE)
#define BLUE    ((1 << 8) - 1)

#define LIGHT_BERRY_RED_2       (0xcc4125)
#define LIGHT_RED_2             (0xe06666)
#define LIGHT_ORANGE_2          (0xf6b26b)
#define LIGHT_YELLOW_2          (0xffd966)
#define LIGHT_GREEN_2           (0x93c47d)
#define LIGHT_CYAN_2            (0x76a5af)
#define LIGHT_CORNFLOWER_BLUE_2 (0x6d9eeb)
#define LIGHT_BLUE_2            (0x6fa8dc)
#define LIGHT_PURPLE_2          (0x8e7cc3)
#define LIGHT_MAGENTA_2         (0xd5a6bd)


#define WIDTH 40
#define HEIGHT 40
#define BPP 4

int main(){
    const char *name = "test.bmp";

    const size_t bpp = BPP;
    const uint32_t width = WIDTH;
    const int32_t height = HEIGHT;

    const uint32_t colors[256] = {LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2, LIGHT_PURPLE_2, LIGHT_CYAN_2, LIGHT_MAGENTA_2, LIGHT_BLUE_2, LIGHT_YELLOW_2, LIGHT_BERRY_RED_2, LIGHT_ORANGE_2, LIGHT_CORNFLOWER_BLUE_2};

    const size_t n = WIDTH*HEIGHT/PIXELS_PER_BYTE(BPP);
    uint8_t arr[(size_t)(WIDTH*HEIGHT/PIXELS_PER_BYTE(BPP))];
    for(size_t i = 0; i < n; ++i){
        size_t aux = ((size_t)(i*PIXELS_PER_BYTE(bpp)))%MAX_COLORS(bpp);
        uint8_t x = 0;
        for(size_t j = 0; j < PIXELS_PER_BYTE(bpp); ++j){
            x <<= bpp;
            x |= (aux + j + ((size_t)((i/(width/PIXELS_PER_BYTE(bpp))))%MAX_COLORS(bpp)) )%MAX_COLORS(bpp);
        }
        arr[i] = x;
    }

    toBmp_bitIndexed(name, n, arr, bpp, width, -height, colors);
    return 0;
}
