#include "toAscii.h"

const char *charAsAsciiStr(uint8_t character){
    switch(character){
    case 0x00: /* ?? */
        return "";
    case 0x49:
        return "\n\n";
    case 0x4E:
        return "\n";
    case 0x4F:
        return "  ";
    case 0x50: /* End of data. */
        return "\0";
    case 0x57:
        return "#";
    case 0x51:
        return "*";
    case 0x52:
        return "A1";
    case 0x53:
        return "A2";
    case 0x54:
        return "POKé";
    case 0x55:
        return "+";
    case 0x58:
        return "$";
    case 0x5F:
        return ".\n";
    case 0x75:
        return "…";
    case 0x7F:
        return " ";
    case 0x80:
        return "A";
    case 0x81:
        return "B";
    case 0x82:
        return "C";
    case 0x83:
        return "D";
    case 0x84:
        return "E";
    case 0x85:
        return "F";
    case 0x86:
        return "G";
    case 0x87:
        return "H";
    case 0x88:
        return "I";
    case 0x89:
        return "J";
    case 0x8A:
        return "K";
    case 0x8B:
        return "L";
    case 0x8C:
        return "M";
    case 0x8D:
        return "N";
    case 0x8E:
        return "O";
    case 0x8F:
        return "P";
    case 0x90:
        return "Q";
    case 0x91:
        return "R";
    case 0x92:
        return "S";
    case 0x93:
        return "T";
    case 0x94:
        return "U";
    case 0x95:
        return "V";
    case 0x96:
        return "W";
    case 0x97:
        return "X";
    case 0x98:
        return "Y";
    case 0x99:
        return "Z";
    case 0x9A:
        return "(";
    case 0x9B:
        return ")";
    case 0x9C:
        return ":";
    case 0x9D:
        return ";";
    case 0x9E:
        return "[";
    case 0x9F:
        return "]";
    case 0xA0:
        return "a";
    case 0xA1:
        return "b";
    case 0xA2:
        return "c";
    case 0xA3:
        return "d";
    case 0xA4:
        return "e";
    case 0xA5:
        return "f";
    case 0xA6:
        return "g";
    case 0xA7:
        return "h";
    case 0xA8:
        return "i";
    case 0xA9:
        return "j";
    case 0xAA:
        return "k";
    case 0xAB:
        return "l";
    case 0xAC:
        return "m";
    case 0xAD:
        return "n";
    case 0xAE:
        return "o";
    case 0xAF:
        return "p";
    case 0xB0:
        return "q";
    case 0xB1:
        return "r";
    case 0xB2:
        return "s";
    case 0xB3:
        return "t";
    case 0xB4:
        return "u";
    case 0xB5:
        return "v";
    case 0xB6:
        return "w";
    case 0xB7:
        return "x";
    case 0xB8:
        return "y";
    case 0xB9:
        return "z";
    case 0xBA:
        return "é";
    case 0xBB:
        return "'d";
    case 0xBC:
        return "'l";
    case 0xBD:
        return "'s";
    case 0xBE:
        return "'t";
    case 0xBF:
        return "'v";
    case 0xE0:
        return "'";
    case 0xE1:
        return "PK";
    case 0xE2:
        return "MN";
    case 0xE3:
        return "-";
    case 0xE4:
        return "'r";
    case 0xE5:
        return "'m";
    case 0xE6:
        return "?";
    case 0xE7:
        return "!";
    case 0xE8:
        return ".";
    case 0xED:
        return "→";
    case 0xEE:
        return "↓";
    case 0xEF:
        return "♂";
    case 0xF0:
        return "¥";
    case 0xF1:
        return "×";
    case 0xF3:
        return "/";
    case 0xF4:
        return ",";
    case 0xF5:
        return "♀";
    case 0xF6:
        return "0";
    case 0xF7:
        return "1";
    case 0xF8:
        return "2";
    case 0xF9:
        return "3";
    case 0xFA:
        return "4";
    case 0xFB:
        return "5";
    case 0xFC:
        return "6";
    case 0xFD:
        return "7";
    case 0xFE:
        return "8";
    case 0xFF:
        return "9";
        
    default:
        break;
    }
    return "(nil)";
}
